#
# Generated by zgen.
# This file will be overwritten the next time you run zgen save

ZSH=/home/sascha/.zgen/robbyrussell/oh-my-zsh-master

#
source "/home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/cabal/cabal.plugin.zsh"
source "/home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/catimg/catimg.plugin.zsh"
source "/home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/colorize/colorize.plugin.zsh"
source "/home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/command-not-found/command-not-found.plugin.zsh"
source "/home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/cp/cp.plugin.zsh"
source "/home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/dircycle/dircycle.plugin.zsh"
source "/home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/grunt/grunt.plugin.zsh"
source "/home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/scd/scd.plugin.zsh"
source "/home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/sudo/sudo.plugin.zsh"
source "/home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/zsh-navigation-tools/zsh-navigation-tools.plugin.zsh"
source "/home/sascha/.zgen/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.plugin.zsh"
source "/home/sascha/.zgen/nojhan/liquidprompt-master/liquidprompt.plugin.zsh"
source "/home/sascha/.zgen/chrissicool/zsh-256color-master/zsh-256color.plugin.zsh"

#
# Add our plugins and completions to fpath
#
fpath=(/home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/cabal /home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/catimg /home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/colorize /home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/command-not-found /home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/cp /home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/dircycle /home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/grunt /home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/scd /home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/sudo /home/sascha/.zgen/robbyrussell/oh-my-zsh-master/plugins/zsh-navigation-tools /home/sascha/.zgen/zsh-users/zsh-syntax-highlighting-master /home/sascha/.zgen/nojhan/liquidprompt-master /home/sascha/.zgen/chrissicool/zsh-256color-master /home/sascha/.zgen/zsh-users/zsh-completions-master/src ${fpath})
