#
# Generated by zgen.
# This file will be overwritten the next time you run zgen save

ZSH=/home/sascha/.config/zsh/zgen/robbyrussell/oh-my-zsh-master

#
source "/home/sascha/.config/zsh/zgen/liquidprompt/liquidprompt-master/liquidprompt.plugin.zsh"
source "/home/sascha/.config/zsh/zgen/chrissicool/zsh-256color-master/zsh-256color.plugin.zsh"
source "/home/sascha/.config/zsh/zgen/robbyrussell/oh-my-zsh-master/plugins/colored-man-pages/colored-man-pages.plugin.zsh"
source "/home/sascha/.config/zsh/zgen/zsh-users/zsh-autosuggestions-master/zsh-autosuggestions.plugin.zsh"
source "/home/sascha/.config/zsh/zgen/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.plugin.zsh"

#
# Add our plugins and completions to fpath
#
fpath=(/home/sascha/.config/zsh/zgen/liquidprompt/liquidprompt-master /home/sascha/.config/zsh/zgen/chrissicool/zsh-256color-master /home/sascha/.config/zsh/zgen/robbyrussell/oh-my-zsh-master/plugins/colored-man-pages /home/sascha/.config/zsh/zgen/zsh-users/zsh-autosuggestions-master /home/sascha/.config/zsh/zgen/zsh-users/zsh-syntax-highlighting-master ${fpath})
